stages:
  - build
  - test

.export_build_jdk: &export_build_jdk
  - export JAVA_HOME=$CI_PROJECT_DIR/build/linux-x86_64-normal-zero-release/images/j2sdk-image

build-jdk:
 stage: build
 script:
  - ./scripts/configure-ci.sh
  - make hotspot jdk images JOBS=24 CONF=linux-x86_64-normal-zero-release
 artifacts:
   paths:
     - build/

#build-shopizer:
#  stage: build
#  script:
#    - git clone git@ipads.se.sjtu.edu.cn:ipads-storage/codebase/wbridge/shopizer.git
#    - cd shopizer
#    - git checkout 73747973c0d938df18caa366a8bd8a20906a9e2a

test-unit:
  stage: test
  script:
    - cd concolic-test
    - *export_build_jdk
    - gradle test

# test-shopizer:
#   stage: test
#   script:
#     - git clone --depth 1 --branch openjdk_concolic_adapt git@ipads.se.sjtu.edu.cn:ipads-storage/codebase/wbridge/shopizer.git
#     - cd shopizer
#     - export JAVA_HOME=$CI_PROJECT_DIR/build/linux-x86_64-normal-zero-release/jdk
#     - cd $CI_PROJECT_DIR/shopizer/sm-shop
#     - mvn test