stages:
  - build
  - test

.export_build_jdk: &export_build_jdk
  - export JAVA_HOME=$CI_PROJECT_DIR/build/linux-x86_64-normal-zero-release/images/j2sdk-image

cache:
  paths:
    - build/linux-x86_64-normal-zero-release/images/j2sdk-image
    - concolic-test/.gradle/caches
    - concolic-test/.gradle/wrapper

build-jdk:
  stage: build
  script:
    - ./scripts/configure-ci.sh
    - make clean JOBS=24 CONF=linux-x86_64-normal-zero-release
    - make hotspot jdk images JOBS=30 CONF=linux-x86_64-normal-zero-release

test-unit:
  stage: test
  script:
    - cd concolic-test
    - *export_build_jdk
#    - ./gradlew test TODO: fix #126 cannot run all tests at once
  - ./gradlew clean test --tests concolic.test.symbolic.BigDecimalTest
  - ./gradlew clean test --tests concolic.test.array.ArrayTest
  - ./gradlew clean test --tests concolic.test.unsafe.UnsafeTest
  - ./gradlew clean test --tests concolic.test.webridge.JavaEntryPointTest
  - ./gradlew clean test --tests concolic.test.webridge.SanityTest

test-shopizer:
  stage: test
  script:
    - git clone --depth 1 --branch openjdk_concolic_adapt git@ipads.se.sjtu.edu.cn:ipads-storage/codebase/wbridge/shopizer.git
    - cd shopizer
    - cd $CI_PROJECT_DIR/shopizer/sm-shop
    - *export_build_jdk
    - mvn test -Dtest="ProductTest" -X